### ISSUE TITLE
 .DS_Storeがある！！！！！！！！

### ISSUE THREAD

**Issue by yudai0804** [hamuchan214/HTmultipurposeboard#1]
.DS_Storeを消してください！！！！
.gitignoreには.DS_Storeが書かれているので、キャッシュが残ってしまっているんだと思います。
参考:https://qiita.com/fuwamaki/items/3ed021163e50beab7154

**Comment by hamuchan214** [comment]
はい

**Comment by hamuchan214** [comment]
.DS_Storeはカス
